addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.1.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.9.2")
addSbtPlugin("com.github.gseitz"  % "sbt-release"              % "1.0.13")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.6.1")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"          % "2.4.8")
