name: sql-formatter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [2.11.12, 2.12.15, 2.13.8]
        project: [sql_formatterJVM, sql_formatterJS, sql_formatterNative]
        coverage: [coverage]
        coverageReport: [coverageReport]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          key: scala-dependencies
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run tests
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          PROJECT: ${{ matrix.project }}
          COVERAGE: ${{ matrix.coverage }}
          COVERAGE_REPORT: ${{ matrix.coverageReport }}
        run: >
          sbt ++$SCALA_VERSION check $COVERAGE $PROJECT/test $COVERAGE_REPORT
      - name: Report to CodeCov
        run: bash <(curl -s https://codecov.io/bash)